apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongo-deployment
  namespace: default
  labels:
    app:  mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongo-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app:  mongo-deployment
    spec:
      containers:
      - name:  mongo-deployment
        image:  mongo
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-root-password
        ports:
        - containerPort:  27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: default
spec:
  selector:
    app: mongo-deployment
  ports:
  - name: mongo-service
    port: 27017
    targetPort: 27017
    protocol: TCP